const REF=['syllabus','concepts','questions','provenance','mapping-history','concept-migrations'];
const KEY='smartprep.personal.v1'; let db={}, personal=loadPersonal(), currentView='overview';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function emptyPersonal(){return{schemaVersion:'1.0.0',attempts:[],errors:[],revisionEvents:[],revisionResults:[],studySessions:[]}}
function loadPersonal(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&x.schemaVersion==='1.0.0'?x:emptyPersonal()}catch{return emptyPersonal()}}
function save(){localStorage.setItem(KEY,JSON.stringify(personal));}
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`, now=()=>new Date().toISOString();
async function load(){const d=await Promise.all(REF.map(n=>fetch(`./public/data/${n}.json`).then(r=>r.json())));[db.syllabus,db.concepts,db.questions,db.provenance,db.history,db.migrations]=d.map(x=>x.records);$('#globalStatus').textContent='VALID DATA';render('overview')}
const concept=id=>db.concepts.find(x=>x.conceptId===id), question=id=>db.questions.find(x=>x.questionId===id), node=id=>db.syllabus.find(x=>x.syllabusNodeId===id);
function crumb(label=''){ $('#breadcrumb').innerHTML=label?`<button data-nav="overview">Home</button><span>›</span><strong>${esc(label)}</strong>`:''; document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>render(b.dataset.nav)) }
function overview(){crumb();return `<h2>SmartPrep overview</h2><div class="cards">${[['Concepts',db.concepts.length],['Questions',db.questions.length],['My attempts',personal.attempts.length],['Open errors',personal.errors.filter(x=>x.resolutionStatus==='OPEN').length],['Revision events',personal.revisionEvents.length],['Study sessions',personal.studySessions.length]].map(x=>`<div class="card"><div class="muted">${x[0]}</div><div class="metric">${x[1]}</div></div>`).join('')}</div><div class="grid" style="margin-top:14px"><div class="panel"><h3>Sprint 4</h3><p>Attempts, errors, revisions and study sessions are stored only in this browser.</p><button data-nav="personal">Open My study data</button></div><div class="panel notice"><h3>Backup reminder</h3><p>Browser storage can be cleared. Export your personal data regularly.</p><button id="quickExport">Export backup</button></div><div class="panel"><h3>Evidence gate</h3><p>Reference evidence remains separate and unchanged. Priority/readiness remain disabled.</p></div></div>`}
function syllabus(){crumb('Syllabus');let roots=db.syllabus.filter(x=>!x.parentNodeId);const tree=n=>`<li><details open><summary>${esc(n.officialTitle)}</summary><div class="muted">${esc(n.officialWording)}</div><ul>${db.concepts.filter(c=>c.syllabusNodeIds.includes(n.syllabusNodeId)).map(c=>`<li><button data-concept="${c.conceptId}">${esc(c.name)}</button></li>`).join('')}${db.syllabus.filter(x=>x.parentNodeId===n.syllabusNodeId).map(tree).join('')}</ul></details></li>`;return `<h2>Official syllabus navigator</h2><div class="panel"><ul>${roots.map(tree).join('')}</ul></div>`}
function conceptCards(items){return items.map(c=>`<article class="card"><code>${c.conceptId}</code><h3>${esc(c.name)}</h3><p>${esc(node(c.syllabusNodeIds[0])?.officialTitle)}</p><button data-concept="${c.conceptId}">Open concept</button></article>`).join('')||'<div class="panel empty">No concepts found.</div>'}
function concepts(){crumb('Concepts');return `<h2>Canonical concepts</h2><div class="toolbar"><input id="cSearch" placeholder="Search name or ID"><select id="cFamily"><option value="">All families</option><option value="ITH">History</option><option value="GEO">Geography</option><option value="SOC">Society</option></select></div><div id="cGrid" class="grid">${conceptCards(db.concepts)}</div>`}
function qrows(items){return items.map(q=>`<tr><td>${q.questionNumber}</td><td><span class="tag ${q.verificationStatus.toLowerCase()}">${q.verificationStatus}</span></td><td>${q.primaryConceptId?`${esc(concept(q.primaryConceptId)?.name)}<br><code>${q.primaryConceptId}</code>`:'<span class="muted">Unmapped</span>'}</td><td>${q.mappingConfidence||'—'}</td><td><button data-question="${q.questionId}">Inspect</button>${q.finalAnswer?` <button data-attempt="${q.questionId}">Attempt</button>`:''}</td></tr>`).join('')}
function questions(){crumb('Question ledger');return `<h2>Question ledger Q1–90</h2><div class="toolbar"><input id="qSearch" placeholder="Question number, ID or concept"><select id="qVerify"><option value="">P and U</option><option>P</option><option>U</option></select></div><div class="scroll"><table><thead><tr><th>Q</th><th>Verification</th><th>Primary concept</th><th>Confidence</th><th>Details</th></tr></thead><tbody id="qRows">${qrows(db.questions)}</tbody></table></div><div id="qDetail" class="detail"></div>`}
function audit(){crumb('Audit trail');return `<h2>Audit trail</h2><div class="grid"><div class="panel"><h3>Provenance</h3><p>${db.provenance.length} append-only reference records.</p></div><div class="panel"><h3>Mapping history</h3>${db.history.map(h=>`<div class="history"><strong>${h.questionId}</strong><p><code>${h.fromConceptId}</code> → <code>${h.toConceptId}</code></p><p>${esc(h.reason)}</p></div>`).join('')}</div></div>`}
function personalPage(){crumb('My study data');return `<h2>My study data</h2><div class="notice"><strong>Local-first:</strong> this information is saved only in this browser on this device.</div><div class="tabs"><button data-p="attempts" class="active">Attempts</button><button data-p="errors">Errors</button><button data-p="revisions">Revisions</button><button data-p="sessions">Sessions</button><button data-p="backup">Backup</button></div><div id="personalPanel"></div>`}
function pAttempts(){return `<div class="panel"><div class="actions"><button id="newAttempt">Add manual attempt</button></div>${personal.attempts.length?`<div class="scroll"><table><thead><tr><th>Date</th><th>Question</th><th>Correct</th><th>Confidence</th><th>Time</th></tr></thead><tbody>${personal.attempts.slice().reverse().map(a=>`<tr><td>${new Date(a.attemptedAt).toLocaleString()}</td><td>${a.questionId}</td><td>${a.correct?'Yes':'No'}</td><td>${a.confidence}/5</td><td>${a.timeSeconds}s</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No attempts recorded.</div>'}</div>`}
function pErrors(){return `<div class="panel">${personal.errors.length?personal.errors.slice().reverse().map(e=>`<div class="history"><strong>${e.errorType} · ${e.conceptId||'Unmapped'}</strong><p>${esc(e.notes||'No note')}</p><span class="tag">${e.resolutionStatus}</span>${e.resolutionStatus==='OPEN'?` <button data-resolve="${e.errorId}">Mark resolved</button>`:''}</div>`).join(''):'<div class="empty">No error records.</div>'}</div>`}
function pRevisions(){return `<div class="panel"><button id="newRevision">Schedule revision</button>${personal.revisionEvents.length?`<div class="scroll"><table><thead><tr><th>Concept</th><th>Scheduled</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody>${personal.revisionEvents.slice().reverse().map(r=>`<tr><td>${esc(concept(r.conceptId)?.name||r.conceptId)}</td><td>${r.scheduledDate}</td><td>${r.revisionType}</td><td>${r.completedDate?'Complete':'Due'}</td><td>${!r.completedDate?`<button data-complete-rev="${r.revisionEventId}">Complete</button>`:'—'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No revisions scheduled.</div>'}</div>`}
function pSessions(){return `<div class="panel"><button id="newSession">Log study session</button>${personal.studySessions.length?personal.studySessions.slice().reverse().map(s=>`<div class="history"><strong>${s.focusedMinutes} focused minutes</strong><p>${new Date(s.startedAt).toLocaleString()} · ${s.sessionType}</p><p>${(s.conceptIds||[]).map(id=>esc(concept(id)?.name||id)).join(', ')||'No concept selected'}</p></div>`).join(''):'<div class="empty">No study sessions recorded.</div>'}</div>`}
function pBackup(){return `<div class="panel"><h3>Backup and restore</h3><div class="actions"><button id="exportData">Export personal backup</button><label class="button">Import backup<input id="importData" type="file" accept="application/json" hidden></label><button id="clearData" class="danger">Clear personal data</button></div><p class="muted">Reference evidence is not changed by personal-data import.</p></div>`}
function showPersonal(tab='attempts'){document.querySelectorAll('[data-p]').forEach(b=>b.classList.toggle('active',b.dataset.p===tab));$('#personalPanel').innerHTML=({attempts:pAttempts,errors:pErrors,revisions:pRevisions,sessions:pSessions,backup:pBackup}[tab])();bindPersonal(tab)}
function modal(title,body,onSave){const wrap=document.createElement('div');wrap.innerHTML=`<div class="panel" style="position:fixed;z-index:20;inset:10% max(3%,calc((100% - 700px)/2));overflow:auto"><h3>${title}</h3>${body}<div class="actions"><button id="mSave">Save</button><button id="mCancel">Cancel</button></div></div><div style="position:fixed;inset:0;background:#0006;z-index:19"></div>`;document.body.append(wrap);wrap.querySelector('#mCancel').onclick=()=>wrap.remove();wrap.querySelector('#mSave').onclick=()=>{if(onSave(wrap)!==false)wrap.remove()}}
function conceptOptions(){return db.concepts.map(c=>`<option value="${c.conceptId}">${esc(c.name)} (${c.conceptId})</option>`).join('')}
function addAttempt(){modal('Record attempt',`<div class="form-grid"><label>Question<select id="aQ">${db.questions.map(q=>`<option value="${q.questionId}">Q${q.questionNumber} · ${esc(concept(q.primaryConceptId)?.name||'Unmapped')}</option>`).join('')}</select></label><label>Correct<select id="aCorrect"><option value="true">Yes</option><option value="false">No</option></select></label><label>Confidence (1–5)<input id="aConf" type="number" min="1" max="5" value="3"></label><label>Time seconds<input id="aTime" type="number" min="0" value="60"></label><label>Guessed<select id="aGuess"><option value="false">No</option><option value="true">Yes</option></select></label></div>`,w=>{let qid=w.querySelector('#aQ').value, att={attemptId:uid('ATT'),questionId:qid,sessionId:null,attemptedAt:now(),selectedAnswer:null,correct:w.querySelector('#aCorrect').value==='true',confidence:+w.querySelector('#aConf').value,timeSeconds:+w.querySelector('#aTime').value,guessed:w.querySelector('#aGuess').value==='true'};personal.attempts.push(att);if(!att.correct){let q=question(qid);personal.errors.push({errorId:uid('ERR'),attemptId:att.attemptId,conceptId:q?.primaryConceptId||null,errorType:'K',notes:'',resolutionStatus:'OPEN',retestDue:null,resolvedAt:null})}save();showPersonal('attempts')})}
function addRevision(){modal('Schedule revision',`<div class="form-grid"><label>Concept<select id="rC">${conceptOptions()}</select></label><label>Date<input id="rD" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Type<select id="rT"><option>CLOSED_BOOK_RECALL</option><option>MCQ_RETEST</option><option>RELEARN</option></select></label></div>`,w=>{personal.revisionEvents.push({revisionEventId:uid('REV'),conceptId:w.querySelector('#rC').value,scheduledDate:w.querySelector('#rD').value,completedDate:null,revisionType:w.querySelector('#rT').value,trigger:'MANUAL',resultScore:null,difficultyRating:null,nextRevisionDate:null});save();showPersonal('revisions')})}
function addSession(){modal('Log study session',`<div class="form-grid"><label>Concept<select id="sC"><option value="">None</option>${conceptOptions()}</select></label><label>Focused minutes<input id="sF" type="number" min="1" value="30"></label><label>Interruption minutes<input id="sI" type="number" min="0" value="0"></label><label>Type<select id="sT"><option>TARGETED_STUDY</option><option>REVISION</option><option>TEST</option></select></label></div>`,w=>{let mins=+w.querySelector('#sF').value;personal.studySessions.push({sessionId:uid('SES'),startedAt:new Date(Date.now()-mins*60000).toISOString(),endedAt:now(),sessionType:w.querySelector('#sT').value,conceptIds:w.querySelector('#sC').value?[w.querySelector('#sC').value]:[],focusedMinutes:mins,interruptionMinutes:+w.querySelector('#sI').value,activityCounts:{recallPrompts:0,questionsAttempted:0,errorsReviewed:0}});save();showPersonal('sessions')})}
function exportData(){let payload={application:'SmartPrep',schemaVersion:'1.0.0',exportedAt:now(),exportReason:'manual',personalData:personal};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download=`smartprep-personal-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function bindPersonal(tab){document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>showPersonal(b.dataset.p));if($('#newAttempt'))$('#newAttempt').onclick=addAttempt;if($('#newRevision'))$('#newRevision').onclick=addRevision;if($('#newSession'))$('#newSession').onclick=addSession;document.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=()=>{let e=personal.errors.find(x=>x.errorId===b.dataset.resolve);e.resolutionStatus='RESOLVED';e.resolvedAt=now();save();showPersonal('errors')});document.querySelectorAll('[data-complete-rev]').forEach(b=>b.onclick=()=>{let r=personal.revisionEvents.find(x=>x.revisionEventId===b.dataset.completeRev);r.completedDate=now();save();showPersonal('revisions')});if($('#exportData'))$('#exportData').onclick=exportData;if($('#clearData'))$('#clearData').onclick=()=>{if(confirm('Clear all personal study data on this browser?')){personal=emptyPersonal();save();showPersonal('backup')}};if($('#importData'))$('#importData').onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());if(x.schemaVersion!=='1.0.0'||!x.personalData)throw Error('Unsupported backup');personal=x.personalData;save();alert('Personal backup imported');showPersonal('backup')}catch(err){alert('Import failed: '+err.message)}}}
function showConcept(id){let c=concept(id), attempts=personal.attempts.filter(a=>question(a.questionId)?.primaryConceptId===id), errs=personal.errors.filter(e=>e.conceptId===id&&e.resolutionStatus==='OPEN');crumb(c.name);$('#view').innerHTML=`<div class="panel"><code>${c.conceptId}</code><h2>${esc(c.name)}</h2><p><strong>Official node:</strong> ${esc(node(c.syllabusNodeIds[0])?.officialTitle)}</p><div class="cards"><div class="card"><div class="muted">Attempts</div><div class="metric">${attempts.length}</div></div><div class="card"><div class="muted">Open errors</div><div class="metric">${errs.length}</div></div><div class="card"><div class="muted">Scheduled revisions</div><div class="metric">${personal.revisionEvents.filter(r=>r.conceptId===id&&!r.completedDate).length}</div></div></div><div class="actions"><button id="cAttempt">Record attempt</button><button id="cRevision">Schedule revision</button><button id="cSession">Log study session</button></div><p class="muted">Personal records are separate from APPSC evidence.</p></div>`;$('#cAttempt').onclick=addAttempt;$('#cRevision').onclick=addRevision;$('#cSession').onclick=addSession}
function showQuestion(id){let q=question(id);$('#qDetail').innerHTML=`<div class="panel"><h3>Q${q.questionNumber} · ${q.questionId}</h3><p><strong>Question text:</strong> ${q.questionText?esc(q.questionText):'<span class="muted">Not available — deliberately null</span>'}</p><p><strong>Primary concept:</strong> ${q.primaryConceptId?esc(concept(q.primaryConceptId)?.name):'Unmapped'}</p><p><strong>Evidence:</strong> ${q.evidenceClass} · <strong>Verification:</strong> ${q.verificationStatus}</p><button id="detailAttempt">Record attempt</button></div>`;$('#detailAttempt').onclick=addAttempt;$('#qDetail').scrollIntoView({behavior:'smooth'})}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>render(b.dataset.nav));document.querySelectorAll('[data-concept]').forEach(b=>b.onclick=()=>showConcept(b.dataset.concept));document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>showQuestion(b.dataset.question));if(currentView==='concepts'){let f=()=>{$('#cGrid').innerHTML=conceptCards(db.concepts.filter(c=>(!$('#cFamily').value||c.conceptId.includes('-'+$('#cFamily').value+'-'))&&(`${c.conceptId} ${c.name}`.toLowerCase().includes($('#cSearch').value.toLowerCase()))));bind()};$('#cSearch').oninput=f;$('#cFamily').onchange=f}if(currentView==='questions'){let f=()=>{$('#qRows').innerHTML=qrows(db.questions.filter(q=>(!$('#qVerify').value||q.verificationStatus===$('#qVerify').value)&&(`${q.questionNumber} ${q.questionId} ${q.primaryConceptId||''} ${concept(q.primaryConceptId)?.name||''}`.toLowerCase().includes($('#qSearch').value.toLowerCase()))));document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>showQuestion(b.dataset.question))};$('#qSearch').oninput=f;$('#qVerify').onchange=f}if(currentView==='personal')showPersonal('attempts');if($('#quickExport'))$('#quickExport').onclick=exportData}
function render(v){currentView=v;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#view').innerHTML=({overview,syllabus,concepts,questions,personal:personalPage,audit}[v]||overview)();bind()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>render(b.dataset.view));load().catch(e=>{$('#globalStatus').textContent='LOAD FAILED';$('#globalStatus').className='pill bad';$('#view').innerHTML=`<pre>${esc(e.stack||e.message)}</pre>`});