import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const DEFAULT_URL="https://ppelqrhsfvcbwrcsovmr.supabase.co", CFG="smartprep.supabase.config.v1", PKEY="smartprep.personal.v1", TKEY="smartprep.tests.v1";
const $=s=>document.querySelector(s); let sb=null,user=null;
const maps={attempts:'attempts',errors:'errors',revisionEvents:'revision_events',revisionResults:'revision_results',studySessions:'study_sessions'};
const uid=(prefix)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
function cfg(){try{return JSON.parse(localStorage.getItem(CFG))||{url:DEFAULT_URL,key:''}}catch{return{url:DEFAULT_URL,key:''}}}
function log(x){$('#log').textContent=`${new Date().toLocaleTimeString()}  ${x}\n`+$('#log').textContent}
function personal(){try{return JSON.parse(localStorage.getItem(PKEY))||{schemaVersion:'1.0.0',attempts:[],errors:[],revisionEvents:[],revisionResults:[],studySessions:[]}}catch{return{schemaVersion:'1.0.0',attempts:[],errors:[],revisionEvents:[],revisionResults:[],studySessions:[]}}}
function tests(){try{return JSON.parse(localStorage.getItem(TKEY))||{schemaVersion:'1.0.0',sessions:[]}}catch{return{schemaVersion:'1.0.0',sessions:[]}}}
function clientId(obj,kind){return obj.clientId||obj.attemptId||obj.errorId||obj.revisionEventId||obj.revisionResultId||obj.sessionId||obj.testSessionId||uid(kind)}
function init(){let c=cfg();$('#url').value=c.url;$('#key').value=c.key;if(c.url&&c.key){sb=createClient(c.url,c.key,{auth:{persistSession:true,detectSessionInUrl:true}});sb.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));sb.auth.getUser().then(({data})=>setUser(data.user))}else setStatus('Enter the publishable key to connect.','warn')}
function setStatus(t){$('#status').textContent=t}
function setUser(u){user=u;$('#auth').hidden=!!u;$('#sync').hidden=!u;$('#who').textContent=u?.email||'—';$('#last').textContent=localStorage.getItem('smartprep.cloud.lastSync')||'Never';$('#count').textContent=countLocal();setStatus(u?`Connected to Supabase as ${u.email}`:'Cloud configured; sign in to sync.')}
function countLocal(){let p=personal(),t=tests();return Object.keys(maps).reduce((n,k)=>n+(p[k]?.length||0),0)+(t.sessions?.length||0)}
async function sign(mode){if(!sb)return alert('Save the connection first.');let email=$('#email').value.trim(),password=$('#password').value;if(!email)return alert('Enter email.');let r;if(mode==='in')r=await sb.auth.signInWithPassword({email,password});if(mode==='up')r=await sb.auth.signUp({email,password,options:{emailRedirectTo:'https://sivakumar-batte.github.io/smartprep/cloud.html'}});if(mode==='reset')r=await sb.auth.resetPasswordForEmail(email,{redirectTo:'https://sivakumar-batte.github.io/smartprep/cloud.html'});if(r.error)alert(r.error.message);else alert(mode==='up'?'Check your email to confirm the account.':mode==='reset'?'Password reset email sent.':'Signed in.')}
function row(obj,kind){return{user_id:user.id,client_id:clientId(obj,kind),payload:obj,updated_at:new Date().toISOString()}}
async function upsert(table,items,kind){if(!items.length)return 0;let {error}=await sb.from(table).upsert(items.map(x=>row(x,kind)),{onConflict:'user_id,client_id'});if(error)throw error;return items.length}
async function push(){let p=personal(),t=tests(),n=0;for(let [k,table] of Object.entries(maps))n+=await upsert(table,p[k]||[],k);n+=await upsert('test_sessions',t.sessions||[],'test');let settings={queue:localStorage.getItem('smartprep.queue.settings.v1'),analytics:localStorage.getItem('smartprep.analytics.settings.v1'),revision:localStorage.getItem('smartprep.revision.settings.v1')};let {error}=await sb.from('user_settings').upsert({user_id:user.id,payload:settings,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;stamp();log(`Uploaded ${n} activity records and settings.`)}
function mergeByClient(local,rows,kind){let m=new Map(local.map(x=>[clientId(x,kind),x]));for(let r of rows)m.set(r.client_id,r.payload);return [...m.values()]}
async function pull(){if(!$('#confirmPull').checked)throw Error('Tick the download confirmation box first.');let p=personal(),t=tests(),n=0;for(let [k,table] of Object.entries(maps)){let {data,error}=await sb.from(table).select('client_id,payload,updated_at');if(error)throw error;p[k]=mergeByClient(p[k]||[],data||[],k);n+=(data||[]).length}let {data,error}=await sb.from('test_sessions').select('client_id,payload,updated_at');if(error)throw error;t.sessions=mergeByClient(t.sessions||[],data||[],'test');n+=(data||[]).length;let s=await sb.from('user_settings').select('payload').maybeSingle();if(s.error)throw s.error;if(s.data?.payload){let x=s.data.payload;if(x.queue)localStorage.setItem('smartprep.queue.settings.v1',x.queue);if(x.analytics)localStorage.setItem('smartprep.analytics.settings.v1',x.analytics);if(x.revision)localStorage.setItem('smartprep.revision.settings.v1',x.revision)}localStorage.setItem(PKEY,JSON.stringify(p));localStorage.setItem(TKEY,JSON.stringify(t));stamp();log(`Downloaded and merged ${n} cloud records.`);$('#count').textContent=countLocal()}
function stamp(){let x=new Date().toLocaleString();localStorage.setItem('smartprep.cloud.lastSync',x);$('#last').textContent=x}
async function run(fn){try{setStatus('Sync in progress…');await fn();setStatus('Sync complete.')}catch(e){setStatus('Sync failed. Local data was kept.');log(`ERROR: ${e.message}`)}}
$('#saveConfig').onclick=()=>{let url=$('#url').value.trim(),key=$('#key').value.trim();if(!url||!key)return alert('Both values are required.');if(key.includes('service_role')||key.startsWith('sb_secret_'))return alert('Do not use a secret/service-role key. Use the publishable key.');localStorage.setItem(CFG,JSON.stringify({url,key}));location.reload()};
$('#forgetConfig').onclick=()=>{localStorage.removeItem(CFG);location.reload()};$('#signin').onclick=()=>sign('in');$('#signup').onclick=()=>sign('up');$('#reset').onclick=()=>sign('reset');$('#signout').onclick=()=>sb.auth.signOut();$('#push').onclick=()=>run(push);$('#pull').onclick=()=>run(pull);$('#both').onclick=()=>run(async()=>{await push();await pull()});init();